// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1FWuir1TF7N17iGGH02WBWDLQ1Ldj2y0',
    appId: '1:935146622990:web:ef379ff41d8f8b455d2c5f',
    messagingSenderId: '935146622990',
    projectId: 'notification-example-5d84b',
    authDomain: 'notification-example-5d84b.firebaseapp.com',
    storageBucket: 'notification-example-5d84b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfBeK3rwQzllderQSHIdUX0evK0cHw54',
    appId: '1:935146622990:android:897561caae35a6e55d2c5f',
    messagingSenderId: '935146622990',
    projectId: 'notification-example-5d84b',
    storageBucket: 'notification-example-5d84b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBULKbCNenWiHUZzZwS6aVSfRL7aiF20i4',
    appId: '1:935146622990:ios:56891f53e8ab97415d2c5f',
    messagingSenderId: '935146622990',
    projectId: 'notification-example-5d84b',
    storageBucket: 'notification-example-5d84b.appspot.com',
    iosClientId: '935146622990-cp5c2308uvj6664k15t5q3jtevdtcuqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotificationExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBULKbCNenWiHUZzZwS6aVSfRL7aiF20i4',
    appId: '1:935146622990:ios:56891f53e8ab97415d2c5f',
    messagingSenderId: '935146622990',
    projectId: 'notification-example-5d84b',
    storageBucket: 'notification-example-5d84b.appspot.com',
    iosClientId: '935146622990-cp5c2308uvj6664k15t5q3jtevdtcuqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotificationExample',
  );
}
